import { countryNameReplacementMap as countryNameReplacementMapSource } from './countryFactNames'
import { providedFactTranslations } from './providedFactTranslations'

export type FactLanguage = 'ru' | 'en' | 'es' | 'fr' | 'de' | 'ro'

export const providedCountryFacts: Record<string, string[]> = {
  af: ['Afghanistan is home to parts of the Hindu Kush mountains.', 'Ancient Silk Road routes crossed the region.', 'Kabul is one of the oldest cities in Asia.'],
  al: ['Albania has thousands of old bunkers.', 'The Albanian Riviera is famous for beaches.', 'Mountains cover much of Albania.'],
  dz: ['Algeria is the largest country in Africa.', 'Most of the country is covered by the Sahara Desert.', 'Oil and gas exports are important there.'],
  ad: ['Andorra lies in the Pyrenees mountains between France and Spain.', 'Ski tourism is very popular there.', 'It is one of Europe\'s microstates.'],
  ao: ['Angola has rich oil reserves.', 'Portuguese is the official language.', 'The country has Atlantic Ocean coastline.'],
  ag: ['Antigua and Barbuda consists of two main islands.', 'Tourism is the largest industry.', 'Cricket is very popular there.'],
  ar: ['Argentina is home to tango dancing.', 'Patagonia is located in the south of the country.', 'Argentina has one of the world\'s strongest football cultures.'],
  am: ['Armenia has its own unique alphabet.', 'Christianity became the state religion very early there.', 'Mount Ararat is a national symbol.'],
  au: ['Australia is both a country and a continent-like landmass.', 'Kangaroos live in the wild there.', 'The Great Barrier Reef is located near Australia.'],
  at: ['Mozart was born in Austria.', 'The Alps cover much of the country.', 'Vienna is famous for classical music.'],
  az: ['Azerbaijan is called the Land of Fire.', 'Baku is located near the Caspian Sea.', 'The country has many mud volcanoes.'],
  bs: ['The Bahamas consists of hundreds of islands.', 'Tourism drives the economy.', 'The water is famous for its bright turquoise color.'],
  bh: ['Bahrain is an island country in the Persian Gulf.', 'Oil helped modernize the country.', 'Formula 1 races are held there.'],
  bd: ['Bangladesh has one of the highest population densities in the world.', 'The Sundarbans mangrove forest is located there.', 'Textile production is very important there.'],
  bb: ['Barbados is known for tropical beaches and resorts.', 'Rihanna was born there.', 'Cricket is very popular on the island.'],
  by: ['Belarus has many forests and lakes.', 'Minsk was rebuilt after World War II.', 'The European bison lives there.'],
  be: ['Belgium is famous for waffles and chocolate.', 'Brussels hosts NATO headquarters and many European institutions.', 'The country has three official languages.'],
  bz: ['Belize has the second-largest barrier reef system in the world.', 'English is the official language.', 'Ancient Maya ruins are located there.'],
  bj: ['Benin is considered the birthplace of Vodun culture.', 'Cotton is an important export.', 'Porto-Novo is the official capital.'],
  bt: ['Bhutan measures happiness through Gross National Happiness.', 'The Himalayas cover much of the country.', 'Traditional culture remains very strong there.'],
  bo: ['Bolivia has two capital cities.', 'Salar de Uyuni is the world\'s largest salt flat.', 'The Andes Mountains cross the country.'],
  ba: ['Sarajevo hosted the 1984 Winter Olympics.', 'The country has Ottoman-era architecture.', 'Mountains cover much of the land.'],
  bw: ['Botswana has large diamond reserves.', 'The Okavango Delta is located there.', 'Wildlife tourism is very important there.'],
  br: ['Brazil is the largest country in South America.', 'The Amazon rainforest covers much of the country.', 'Football is extremely popular there.'],
  bn: ['Brunei is a wealthy oil-producing country.', 'The Sultan has one of the largest palaces in the world.', 'The country is located on Borneo island.'],
  bg: ['Bulgaria uses the Cyrillic alphabet.', 'The country is one of Europe\'s oldest states.', 'Rose oil production is famous there.'],
  bf: ['Burkina Faso is located in West Africa.', 'Gold mining is important there.', 'Ouagadougou is the capital city.'],
  bi: ['Burundi is one of Africa\'s smallest countries.', 'Coffee is a major export.', 'Lake Tanganyika borders the country.'],
  kh: ['Angkor Wat is located in Cambodia.', 'The Khmer Empire once ruled much of Southeast Asia.', 'Phnom Penh is the capital city.'],
  cm: ['Cameroon is called Africa in miniature because of its geography.', 'Both English and French are official languages.', 'Mount Cameroon is an active volcano.'],
  ca: ['Canada is the second-largest country in the world.', 'Hockey is the national winter sport.', 'The country has more lakes than any other nation.'],
  cv: ['Cape Verde is an island nation in the Atlantic Ocean.', 'The country has volcanic landscapes.', 'Tourism is important to the economy.'],
  cf: ['The Central African Republic is rich in natural resources.', 'Rainforests cover parts of the country.', 'Bangui is the capital city.'],
  td: ['Much of Chad is desert.', 'Lake Chad has shrunk dramatically over time.', 'Oil production is important to the economy.'],
  cl: ['Chile is one of the longest countries in the world.', 'The Atacama Desert is one of the driest places on Earth.', 'Easter Island belongs to Chile.'],
  cn: ['China has the world\'s largest population.', 'The Great Wall is located there.', 'Paper was invented in ancient China.'],
  co: ['Colombia is famous for coffee production.', 'Bogota is one of the highest capitals in the world.', 'The country has Caribbean and Pacific coastlines.'],
  km: ['Comoros is an island nation in the Indian Ocean.', 'Volcanoes shaped many of the islands.', 'Vanilla production is important there.'],
  cr: ['Costa Rica has no standing army.', 'The country is famous for biodiversity.', 'Ecotourism is very popular there.'],
  hr: ['Dubrovnik was used in Game of Thrones filming.', 'Croatia has over a thousand islands.', 'The necktie originated there.'],
  cu: ['Cuba is the largest Caribbean island nation.', 'Old American cars are common there.', 'Havana is famous for colorful architecture.'],
  cy: ['Cyprus is divided into two parts.', 'The island has Mediterranean beaches.', 'According to legend, Aphrodite was born there.'],
  cz: ['Prague is famous for its old architecture.', 'Beer culture is very strong there.', 'Czechia has many castles.'],
  dk: ['LEGO was invented in Denmark.', 'Copenhagen is bicycle-friendly.', 'Denmark is one of the happiest countries in the world.'],
  dj: ['Djibouti sits near major shipping routes.', 'Lake Assal is one of the saltiest lakes in the world.', 'The climate is extremely hot and dry.'],
  dm: ['Dominica is known as the Nature Island.', 'Rainforests cover much of the land.', 'Boiling Lake is located there.'],
  do: ['The Dominican Republic shares Hispaniola island with Haiti.', 'Tourism is a major industry.', 'Baseball is extremely popular there.'],
  cd: ['The Congo Rainforest is located there.', 'The country is rich in minerals.', 'The Congo River flows through it.'],
  ec: ['The equator passes through Ecuador.', 'The Galapagos Islands belong to Ecuador.', 'Quito is located high in the Andes.'],
  eg: ['The pyramids are located in Egypt.', 'The Nile River flows through the country.', 'Ancient Egyptian civilization is one of the oldest in history.'],
  sv: ['El Salvador is the smallest country in Central America.', 'Volcanoes are common there.', 'The country uses Bitcoin as legal tender.'],
  gq: ['Spanish is an official language there.', 'Oil exports dominate the economy.', 'The country includes islands and mainland territory.'],
  er: ['Eritrea borders the Red Sea.', 'Italian architecture remains in some cities.', 'Independence was achieved in 1993.'],
  ee: ['Estonia is highly digitalized.', 'Skype was developed by Estonian programmers.', 'Tallinn has a well-preserved medieval old town.'],
  sz: ['Eswatini is one of Africa\'s last absolute monarchies.', 'The country was formerly called Swaziland.', 'Traditional festivals are important there.'],
  et: ['Coffee originated in Ethiopia.', 'Addis Ababa hosts the African Union headquarters.', 'The country has its own calendar.'],
  fj: ['Fiji consists of hundreds of islands.', 'Rugby is very popular there.', 'The country is known for coral reefs.'],
  fi: ['Finland is called the Land of a Thousand Lakes.', 'Saunas are part of daily culture.', 'The country regularly ranks highly in happiness reports.'],
  fr: ['France is one of the most visited countries in the world.', 'The Eiffel Tower is located in Paris.', 'France is famous for cheese and wine.'],
  ga: ['Gabon has large rainforest areas.', 'The country is rich in oil.', 'Wildlife parks attract tourists.'],
  gm: ['The Gambia follows the Gambia River.', 'It is mainland Africa\'s smallest country.', 'Tourism is important there.'],
  ge: ['Georgia is one of the oldest wine-producing regions.', 'The Caucasus Mountains run through the country.', 'Tbilisi is known for colorful architecture.'],
  de: ['Germany has sections of highway without speed limits.', 'The printing press was invented there.', 'The country is famous for engineering.'],
  gh: ['Ghana was the first sub-Saharan African country to gain independence.', 'Cocoa production is important there.', 'Accra is the capital city.'],
  gr: ['The Olympic Games began in Greece.', 'The country has thousands of islands.', 'Athens is one of the world\'s oldest cities.'],
  gd: ['Grenada is known as the Spice Island.', 'Nutmeg is a major export.', 'Beautiful Caribbean beaches attract tourists.'],
  gt: ['Ancient Maya civilization flourished in Guatemala.', 'Volcanoes surround many cities.', 'Lake Atitlan is a famous landmark.'],
  gn: ['Guinea has rich bauxite reserves.', 'Conakry is the capital city.', 'Rainforests exist in the south.'],
  gw: ['Guinea-Bissau has many islands.', 'Cashew nuts are a major export.', 'Portuguese is the official language.'],
  gy: ['Guyana is the only English-speaking country in South America.', 'Dense rainforests cover much of the land.', 'Kaieteur Falls is one of the tallest waterfalls in the world.'],
  ht: ['Haiti shares Hispaniola island with the Dominican Republic.', 'It was the first independent Black republic.', 'French and Haitian Creole are official languages.'],
  hn: ['Honduras has Caribbean coastline.', 'Coffee exports are important there.', 'Ancient Maya ruins attract tourists.'],
  hu: ['The Rubik\'s Cube was invented in Hungary.', 'Budapest is famous for thermal baths.', 'Hungarian cuisine includes goulash.'],
  is: ['Iceland uses geothermal energy extensively.', 'Volcanoes and glaciers shape the landscape.', 'Northern lights can often be seen there.'],
  in: ['India is the world\'s largest democracy.', 'The Taj Mahal is located there.', 'The country has hundreds of languages.'],
  id: ['Indonesia is made up of thousands of islands.', 'Komodo dragons live there.', 'Jakarta is one of the world\'s largest cities.'],
  ir: ['Persia is the historical name of Iran.', 'The country has ancient cultural sites.', 'Iran has large oil and gas reserves.'],
  iq: ['Ancient Mesopotamia was located in Iraq.', 'The Tigris and Euphrates rivers flow through the country.', 'Baghdad was once a center of science and culture.'],
  ie: ['Ireland is known for green landscapes.', 'Halloween traditions originated there.', 'The harp is a national symbol.'],
  il: ['Jerusalem is sacred to multiple religions.', 'The Dead Sea is located there.', 'Israel is known for technology startups.'],
  it: ['Pizza originated in Italy.', 'Rome was the center of the Roman Empire.', 'Venice is built on canals.'],
  ci: ['Ivory Coast is one of the world\'s largest cocoa producers.', 'Abidjan is a major African city.', 'French is the official language.'],
  jm: ['Reggae music originated in Jamaica.', 'Usain Bolt was born there.', 'The island is famous for beaches and mountains.'],
  jp: ['Japan consists of thousands of islands.', 'Bullet trains are famous there.', 'Sushi originated in Japan.'],
  jo: ['Petra is located in Jordan.', 'The Dead Sea borders the country.', 'Amman is the capital city.'],
  kz: ['Kazakhstan is the largest landlocked country in the world.', 'The Baikonur Cosmodrome is located there.', 'Much of the country is steppe.'],
  ke: ['Kenya is famous for safaris.', 'The Great Rift Valley runs through the country.', 'Nairobi is a major African city.'],
  ki: ['Kiribati spans across four hemispheres.', 'Rising sea levels threaten the islands.', 'The country consists of coral atolls.'],
  kw: ['Kuwait has major oil reserves.', 'Kuwait City is known for modern buildings.', 'The country borders the Persian Gulf.'],
  kg: ['Mountains cover most of Kyrgyzstan.', 'Nomadic culture remains important.', 'Bishkek is the capital city.'],
  la: ['Laos is Southeast Asia\'s only landlocked country.', 'The Mekong River flows through it.', 'Buddhism is very important there.'],
  lv: ['Latvia has many forests.', 'Riga is famous for art nouveau architecture.', 'Folk music traditions are important there.'],
  lb: ['Lebanon is famous for cedar trees.', 'Beirut is called the Paris of the Middle East.', 'The country has Mediterranean coastline.'],
  ls: ['Lesotho is completely surrounded by South Africa.', 'The entire country lies at high elevation.', 'Horses are often used for transport in mountain regions.'],
  lr: ['Liberia was founded by freed American slaves.', 'Monrovia is named after a U.S. president.', 'English is the official language.'],
  ly: ['Libya has one of the largest oil reserves in Africa.', 'Most of the country is desert.', 'Tripoli is the capital city.'],
  li: ['Liechtenstein is located in the Alps.', 'The country has no airport.', 'It is one of Europe\'s smallest states.'],
  lt: ['Basketball is extremely popular in Lithuania.', 'Vilnius has a large old town.', 'Lithuania was once one of Europe\'s largest states.'],
  lu: ['Luxembourg is one of Europe\'s smallest countries.', 'Public transport is free there.', 'The country has a very high income level.'],
  mg: ['Many animals in Madagascar exist nowhere else.', 'Lemurs are native to Madagascar.', 'The island separated from mainland Africa millions of years ago.'],
  mw: ['Lake Malawi is one of Africa\'s largest lakes.', 'Fishing is important there.', 'Malawi is called the Warm Heart of Africa.'],
  my: ['Malaysia has tropical rainforests.', 'Kuala Lumpur is famous for the Petronas Towers.', 'The country has strong cultural diversity.'],
  mv: ['The Maldives is made up of coral islands.', 'It is one of the world\'s lowest countries.', 'Tourism is central to the economy.'],
  ml: ['Timbuktu is located in Mali.', 'Ancient trade routes crossed the country.', 'The Niger River is important there.'],
  mt: ['Malta is an island country in the Mediterranean.', 'Ancient temples are located there.', 'Many movies were filmed there.'],
  mh: ['The Marshall Islands are made of coral atolls.', 'Climate change is a major concern there.', 'The country has strong ties with the United States.'],
  mr: ['Mauritania is mostly desert.', 'Iron ore exports are important there.', 'The country lies in northwest Africa.'],
  mu: ['Mauritius is famous for beaches and reefs.', 'The extinct dodo bird lived there.', 'The island has multicultural traditions.'],
  mx: ['Mexico is home to ancient Maya and Aztec sites.', 'Tacos originated there.', 'Mexico City is one of the largest cities in the world.'],
  fm: ['Micronesia consists of many Pacific islands.', 'Fishing is important there.', 'The country has tropical climate.'],
  md: ['Moldova is known for wine production.', 'Chisinau is the capital city.', 'Huge underground wine cellars are located there.'],
  mc: ['Monaco is one of the world\'s smallest countries.', 'The Monaco Grand Prix is held there.', 'Many millionaires live there.'],
  mn: ['Mongolia has vast grasslands and steppes.', 'Genghis Khan founded the Mongol Empire.', 'Nomadic traditions remain important there.'],
  me: ['Montenegro has Adriatic Sea coastline.', 'Kotor is famous for medieval architecture.', 'Mountains inspired the country\'s name.'],
  ma: ['Morocco has markets called souks.', 'The Sahara Desert reaches the country.', 'Marrakech is known for colorful streets.'],
  mz: ['Mozambique has Indian Ocean coastline.', 'Portuguese is the official language.', 'Seafood is important in local cuisine.'],
  mm: ['Myanmar was formerly called Burma.', 'Bagan is famous for ancient temples.', 'The country has many ethnic groups.'],
  na: ['Namibia has the Namib Desert.', 'It has one of the lowest population densities in the world.', 'Wildlife tourism is important there.'],
  nr: ['Nauru is one of the world\'s smallest countries.', 'Phosphate mining once made it wealthy.', 'The country is a single island nation.'],
  np: ['Mount Everest is located there.', 'Nepal has many Hindu and Buddhist temples.', 'Kathmandu is the capital city.'],
  nl: ['Much of the Netherlands lies below sea level.', 'Bicycles are extremely common there.', 'Amsterdam has many canals.'],
  nz: ['New Zealand was used in Lord of the Rings filming.', 'Kiwi birds are native there.', 'The country has dramatic natural landscapes.'],
  ni: ['Nicaragua has many lakes and volcanoes.', 'Lake Nicaragua is one of the largest lakes in the Americas.', 'Managua is the capital city.'],
  ne: ['Much of Niger is covered by desert.', 'The Niger River flows through the country.', 'Uranium mining is important there.'],
  ng: ['Nigeria has the largest population in Africa.', 'Nollywood is one of the biggest film industries.', 'Lagos is a massive urban center.'],
  kp: ['North Korea is highly isolated.', 'Pyongyang is the capital city.', 'The country has strict government control.'],
  mk: ['Lake Ohrid is one of Europe\'s oldest lakes.', 'Mountains cover much of North Macedonia.', 'Skopje is the capital city.'],
  no: ['Norway is famous for fjords.', 'The midnight sun occurs in the north.', 'Northern lights can often be seen there.'],
  om: ['Oman has a long maritime history.', 'Muscat is the capital city.', 'Deserts and mountains shape the country.'],
  pk: ['Pakistan is home to K2 mountain.', 'The Indus River flows through the country.', 'Cricket is extremely popular there.'],
  pw: ['Palau is famous for diving tourism.', 'Jellyfish Lake is located there.', 'Marine biodiversity is extremely rich.'],
  pa: ['The Panama Canal connects two oceans.', 'Panama City has a modern skyline.', 'Tropical rainforests cover parts of the country.'],
  pg: ['Hundreds of languages are spoken in Papua New Guinea.', 'Dense jungles cover much of the country.', 'The nation occupies part of New Guinea island.'],
  py: ['Paraguay has two official languages.', 'The country is landlocked.', 'Hydroelectric power is important there.'],
  pe: ['Machu Picchu is located in Peru.', 'The Andes Mountains cross the country.', 'Peru is famous for llamas and alpacas.'],
  ph: ['The Philippines consists of thousands of islands.', 'Basketball is very popular there.', 'The country often experiences typhoons.'],
  pl: ['Warsaw was rebuilt after World War II.', 'Poland is the birthplace of Copernicus.', 'Pierogi are traditional Polish food.'],
  pt: ['Portugal helped lead the Age of Exploration.', 'Lisbon is older than Rome.', 'Port wine comes from Portugal.'],
  qa: ['Qatar hosted the 2022 FIFA World Cup.', 'Doha is the capital city.', 'The country is one of the richest per person.'],
  cg: ['Rainforests cover much of the Republic of the Congo.', 'Brazzaville is the capital city.', 'The Congo River flows nearby.'],
  ro: ['Romania is associated with Dracula legends.', 'The Carpathian Mountains cross the country.', 'Romanian internet speeds are among Europe\'s fastest.'],
  ru: ['Russia is the largest country in the world.', 'It spans Europe and Asia.', 'Lake Baikal is the deepest lake on Earth.'],
  rw: ['Rwanda is called the Land of a Thousand Hills.', 'Mountain gorillas live there.', 'Kigali is known for cleanliness.'],
  kn: ['Saint Kitts and Nevis is the smallest country in the Americas.', 'Tourism is very important there.', 'The islands have volcanic origins.'],
  lc: ['The Pitons are famous volcanic peaks in Saint Lucia.', 'Tourism drives the economy.', 'The island has tropical rainforests.'],
  vc: ['Saint Vincent and the Grenadines consists of many islands.', 'Volcanoes shaped the landscape.', 'Sailing tourism is popular there.'],
  ws: ['Samoa is located in the Pacific Ocean.', 'Rugby is popular there.', 'Traditional culture remains strong.'],
  sm: ['San Marino is surrounded by Italy.', 'It is one of the world\'s oldest republics.', 'Medieval towers overlook the capital.'],
  st: ['Sao Tome and Principe is one of Africa\'s smallest countries.', 'Cocoa production is important there.', 'The country consists of tropical islands.'],
  sa: ['Mecca is located in Saudi Arabia.', 'The country has vast deserts.', 'Oil exports are extremely important there.'],
  sn: ['Dakar is the westernmost major city in Africa.', 'Music and dance are central to culture.', 'The country is known for football fans.'],
  rs: ['Belgrade is one of Europe\'s oldest cities.', 'The Danube River flows through Serbia.', 'Serbian cuisine includes many grilled dishes.'],
  sc: ['Seychelles is made up of many islands.', 'Giant tortoises live there.', 'Tourism is a key industry.'],
  sl: ['Sierra Leone is known for diamond mining.', 'Freetown was founded for freed slaves.', 'Atlantic beaches attract visitors.'],
  sg: ['Singapore is a global financial hub.', 'The country is very clean and modern.', 'Marina Bay Sands is a famous landmark.'],
  sk: ['Slovakia has many castles.', 'The Tatra Mountains are located there.', 'Bratislava borders two countries.'],
  si: ['More than half of Slovenia is forested.', 'Lake Bled is a famous destination.', 'The country has many caves.'],
  sb: ['The Solomon Islands are located in the Pacific Ocean.', 'Important World War II battles happened there.', 'Fishing is important to the economy.'],
  so: ['Somalia has Africa\'s longest mainland coastline.', 'Mogadishu is the capital city.', 'Camels are important in Somali culture.'],
  za: ['South Africa has three capital cities.', 'The country is famous for wildlife safaris.', 'Nelson Mandela was born there.'],
  kr: ['K-pop became globally popular in South Korea.', 'Seoul is a major technology center.', 'Korean cuisine includes kimchi.'],
  ss: ['South Sudan became independent in 2011.', 'Juba is the capital city.', 'The White Nile flows through the country.'],
  es: ['Spain is famous for flamenco dancing.', 'The country produces large amounts of olive oil.', 'Barcelona is known for Gaudi architecture.'],
  lk: ['Sri Lanka is famous for tea production.', 'Ancient temples are located there.', 'The island lies near India.'],
  sd: ['The Nile River flows through Sudan.', 'Sudan has more pyramids than Egypt.', 'Khartoum is located where two Nile rivers meet.'],
  sr: ['Suriname is the smallest country in South America.', 'Dutch is the official language.', 'Much of the country is rainforest.'],
  se: ['IKEA originated in Sweden.', 'Sweden is known for innovation.', 'ABBA came from Sweden.'],
  ch: ['Switzerland is famous for watches and chocolate.', 'The Alps cover much of the country.', 'The country is known for neutrality.'],
  sy: ['Syria has ancient historical cities.', 'Damascus is one of the oldest cities in the world.', 'The country has rich cultural history.'],
  tj: ['Tajikistan is highly mountainous.', 'The Pamir Highway crosses the country.', 'Persian culture strongly influenced the region.'],
  tz: ['Mount Kilimanjaro is located there.', 'Zanzibar belongs to Tanzania.', 'Serengeti National Park is world famous.'],
  th: ['Thailand is famous for street food.', 'Bangkok is one of the world\'s most visited cities.', 'Elephants are important in Thai culture.'],
  tl: ['Timor-Leste became independent in 2002.', 'Portuguese is an official language.', 'Coffee exports are important there.'],
  tg: ['Togo is a narrow West African country.', 'Lome is the capital city.', 'Phosphate mining is important there.'],
  to: ['Tonga is a Polynesian kingdom.', 'The country has many islands.', 'Rugby is very popular there.'],
  tt: ['Carnival celebrations are world famous in Trinidad and Tobago.', 'Oil and gas are important industries.', 'Steelpan music originated there.'],
  tn: ['Carthage was located in modern Tunisia.', 'The Sahara Desert reaches the country.', 'Tunis is the capital city.'],
  tr: ['Istanbul lies in both Europe and Asia.', 'Turkey is famous for bazaars and tea.', 'Ancient Troy was located there.'],
  tm: ['Turkmenistan has huge gas reserves.', 'Ashgabat is known for white marble buildings.', 'Much of the country is desert.'],
  tv: ['Tuvalu is threatened by rising sea levels.', 'It is one of the least populated countries.', 'The nation consists of coral islands.'],
  ug: ['Uganda is home to part of Lake Victoria.', 'Gorilla trekking attracts tourists.', 'The country is crossed by the equator.'],
  ua: ['Ukraine is one of Europe\'s largest countries.', 'Kyiv has deep historical roots.', 'Borscht is an important traditional dish.'],
  ae: ['Dubai has the Burj Khalifa.', 'Artificial islands were built there.', 'Oil wealth rapidly modernized the country.'],
  gb: ['Big Ben is located in London.', 'The country uses left-side driving.', 'Shakespeare came from England.'],
  us: ['The United States has 50 states.', 'Hollywood is located there.', 'The country has the world\'s largest economy.'],
  uy: ['Uruguay legalized cannabis nationwide.', 'Football is very popular there.', 'Montevideo is the capital city.'],
  uz: ['Samarkand was an important Silk Road city.', 'Uzbekistan has impressive Islamic architecture.', 'The country is doubly landlocked.'],
  vu: ['Vanuatu has active volcanoes.', 'The country consists of many islands.', 'Traditional land diving inspired bungee jumping.'],
  va: ['Vatican City is the smallest country in the world.', 'The Pope lives there.', 'The Sistine Chapel is located there.'],
  ve: ['Angel Falls is the world\'s tallest waterfall.', 'Venezuela has large oil reserves.', 'Caracas is the capital city.'],
  vn: ['Vietnam is one of the largest coffee exporters.', 'Hanoi is the capital city.', 'Motorbikes are extremely common there.'],
  ye: ['Yemen has ancient desert cities.', 'Coffee trading historically connected to Yemen.', 'Sana\'a has unique architecture.'],
  zm: ['Victoria Falls borders Zambia.', 'Copper mining is important there.', 'The Zambezi River flows through the country.'],
  zw: ['Great Zimbabwe ruins are located there.', 'Victoria Falls is partly in Zimbabwe.', 'Safari tourism is important there.'],
}

const translatedFactOverrides: Partial<Record<string, Partial<Record<FactLanguage, string[]>>>> = {
  hr: {
    ru: [
      'Дубровник использовали для съёмок «Игры престолов».',
      'У Хорватии больше тысячи островов.',
      'Галстук появился именно в Хорватии.',
    ],
    es: [
      'Dubrovnik se usó en el rodaje de Juego de Tronos.',
      'Croacia tiene más de mil islas.',
      'La corbata se originó allí.',
    ],
    fr: [
      'Dubrovnik a servi au tournage de Game of Thrones.',
      'La Croatie compte plus de mille îles.',
      'La cravate y trouve son origine.',
    ],
    de: [
      'Dubrovnik wurde für Dreharbeiten von Game of Thrones genutzt.',
      'Kroatien hat mehr als tausend Inseln.',
      'Die Krawatte entstand dort.',
    ],
    ro: [
      'Dubrovnik a fost folosit la filmarea Game of Thrones.',
      'Croația are peste o mie de insule.',
      'Cravata își are originea acolo.',
    ],
  },
}

const factReplacementMap: Record<Exclude<FactLanguage, 'en'>, Array<[string, string]>> = {
  ru: [
    ['The country is one of the richest per person.', 'Страна входит в число самых богатых по доходу на человека.'],
    ['The country regularly ranks highly in happiness reports.', 'Страна регулярно занимает высокие места в рейтингах счастья.'],
    ['The country has one of the world\'s strongest football cultures.', 'В стране одна из самых сильных футбольных культур мира.'],
    ['The country has hundreds of languages.', 'В стране сотни языков.'],
    ['The country has many ethnic groups.', 'В стране живёт много этнических групп.'],
    ['The country has strict government control.', 'В стране действует очень строгий государственный контроль.'],
    ['The country often experiences typhoons.', 'Страна часто сталкивается с тайфунами.'],
    ['The country consists of coral atolls.', 'Страна состоит из коралловых атоллов.'],
    ['The country consists of tropical islands.', 'Страна состоит из тропических островов.'],
    ['The country consists of many islands.', 'Страна состоит из множества островов.'],
    ['The country has volcanic landscapes.', 'В стране много вулканических пейзажей.'],
    ['The country has Mediterranean coastline.', 'У страны есть средиземноморское побережье.'],
    ['The country has Atlantic Ocean coastline.', 'У страны есть побережье Атлантического океана.'],
    ['The country has Caribbean and Pacific coastlines.', 'У страны есть побережья Карибского моря и Тихого океана.'],
    ['The country borders the Persian Gulf.', 'Страна граничит с Персидским заливом.'],
    ['The country is famous for biodiversity.', 'Страна известна огромным биоразнообразием.'],
    ['The country is rich in minerals.', 'Страна богата полезными ископаемыми.'],
    ['The country is rich in oil.', 'Страна богата нефтью.'],
    ['The country is known for coral reefs.', 'Страна известна коралловыми рифами.'],
    ['The country is known for football fans.', 'Страна известна футбольными фанатами.'],
    ['The country is crossed by the equator.', 'Через страну проходит экватор.'],
    ['The country is a single island nation.', 'Страна состоит из одного острова.'],
    ['The island has tropical rainforests.', 'На острове есть тропические леса.'],
    ['The island has multicultural traditions.', 'На острове сильны мультикультурные традиции.'],
    ['The island lies near India.', 'Остров расположен рядом с Индией.'],
    ['The island separated from mainland Africa millions of years ago.', 'Остров отделился от материковой Африки миллионы лет назад.'],
    ['Tourism is the largest industry.', 'Туризм является крупнейшей отраслью.'],
    ['Tourism is a major industry.', 'Туризм является важной отраслью.'],
    ['Tourism drives the economy.', 'Туризм сильно поддерживает экономику.'],
    ['Tourism is central to the economy.', 'Туризм играет центральную роль в экономике.'],
    ['Tourism is important to the economy.', 'Туризм важен для экономики.'],
    ['Tourism is very important there.', 'Туризм там очень важен.'],
    ['Tourism is a key industry.', 'Туризм является ключевой отраслью.'],
    ['Wildlife tourism is very important there.', 'Туризм, связанный с дикой природой, там очень важен.'],
    ['Wildlife tourism is important there.', 'Туризм, связанный с дикой природой, там важен.'],
    ['Ecotourism is very popular there.', 'Экотуризм там очень популярен.'],
    ['Sailing tourism is popular there.', 'Парусный туризм там популярен.'],
    ['Fishing is important to the economy.', 'Рыболовство важно для экономики.'],
    ['Fishing is important there.', 'Рыболовство там важно.'],
    ['Coffee exports are important there.', 'Экспорт кофе там важен.'],
    ['Coffee is a major export.', 'Кофе является важной экспортной культурой.'],
    ['Cotton is an important export.', 'Хлопок является важным экспортным товаром.'],
    ['Cocoa production is important there.', 'Производство какао там важно.'],
    ['Textile production is very important there.', 'Текстильное производство там очень важно.'],
    ['Oil production is important to the economy.', 'Добыча нефти важна для экономики.'],
    ['Oil exports dominate the economy.', 'Нефтяной экспорт доминирует в экономике.'],
    ['Oil exports are extremely important there.', 'Экспорт нефти там крайне важен.'],
    ['Oil wealth rapidly modernized the country.', 'Нефтяное богатство быстро модернизировало страну.'],
    ['Oil helped modernize the country.', 'Нефть помогла модернизировать страну.'],
    ['Gold mining is important there.', 'Добыча золота там важна.'],
    ['Diamond mining.', 'добычей алмазов.'],
    ['Copper mining is important there.', 'Добыча меди там важна.'],
    ['Uranium mining is important there.', 'Добыча урана там важна.'],
    ['Phosphate mining is important there.', 'Добыча фосфатов там важна.'],
    ['Iron ore exports are important there.', 'Экспорт железной руды там важен.'],
    ['Natural gas reserves.', 'запасами природного газа.'],
    ['major oil reserves.', 'крупные запасы нефти.'],
    ['large oil reserves.', 'крупные запасы нефти.'],
    ['large natural gas reserves.', 'крупные запасы природного газа.'],
    ['huge gas reserves.', 'огромные запасы газа.'],
    ['has rich oil reserves.', 'имеет богатые запасы нефти.'],
    ['has large oil reserves.', 'имеет крупные запасы нефти.'],
    ['has major oil reserves.', 'имеет большие запасы нефти.'],
    ['has large diamond reserves.', 'имеет крупные запасы алмазов.'],
    ['has rich bauxite reserves.', 'имеет богатые запасы бокситов.'],
    ['has one of the largest oil reserves in Africa.', 'имеет одни из крупнейших запасов нефти в Африке.'],
    ['is the official language.', 'является официальным языком.'],
    ['are official languages.', 'являются официальными языками.'],
    ['Both English and French are official languages.', 'Английский и французский являются официальными языками.'],
    ['French is the official language.', 'Французский является официальным языком.'],
    ['Portuguese is the official language.', 'Португальский является официальным языком.'],
    ['Spanish is an official language there.', 'Испанский там является официальным языком.'],
    ['English is the official language.', 'Английский является официальным языком.'],
    ['French and Haitian Creole are official languages.', 'Французский и гаитянский креольский являются официальными языками.'],
    ['Portuguese is an official language.', 'Португальский является одним из официальных языков.'],
    ['The capital city.', 'столица.'],
    ['is the capital city.', 'является столицей.'],
    ['Minsk was rebuilt after World War II.', 'Минск был восстановлен после Второй мировой войны.'],
    ['Warsaw was rebuilt after World War II.', 'Варшава была восстановлена после Второй мировой войны.'],
    ['hosted the 1984 Winter Olympics.', 'принимал зимние Олимпийские игры 1984 года.'],
    ['hosted the 2022 FIFA World Cup.', 'принимал чемпионат мира по футболу 2022 года.'],
    ['Formula 1 races are held there.', 'Там проходят гонки Формулы-1.'],
    ['The Monaco Grand Prix is held there.', 'Там проходит Гран-при Монако.'],
    ['Cricket is very popular there.', 'Крикет там очень популярен.'],
    ['Cricket is very popular on the island.', 'Крикет очень популярен на острове.'],
    ['Rugby is very popular there.', 'Регби там очень популярно.'],
    ['Rugby is popular there.', 'Регби там популярно.'],
    ['Basketball is very popular there.', 'Баскетбол там очень популярен.'],
    ['Basketball is extremely popular in Lithuania.', 'Баскетбол чрезвычайно популярен в Литве.'],
    ['Football is extremely popular there.', 'Футбол там чрезвычайно популярен.'],
    ['Baseball is extremely popular there.', 'Бейсбол там чрезвычайно популярен.'],
    ['Hockey is the national winter sport.', 'Хоккей является национальным зимним видом спорта.'],
    ['K-pop became globally popular in South Korea.', 'K-pop стал всемирно популярным в Южной Корее.'],
    ['Reggae music originated in Jamaica.', 'Музыка регги появилась на Ямайке.'],
    ['Steelpan music originated there.', 'Музыка стилпан появилась там.'],
    ['The Rubik\'s Cube was invented in Hungary.', 'Кубик Рубика был изобретён в Венгрии.'],
    ['LEGO was invented in Denmark.', 'LEGO был придуман в Дании.'],
    ['Paper was invented in ancient China.', 'Бумага была изобретена в древнем Китае.'],
    ['The printing press was invented there.', 'Печатный станок был изобретён там.'],
    ['Sushi originated in Japan.', 'Суши появились в Японии.'],
    ['Pizza originated in Italy.', 'Пицца появилась в Италии.'],
    ['Tacos originated there.', 'Тако появились там.'],
    ['The necktie originated there.', 'Галстук появился там.'],
    ['Bungee jumping.', 'банджи-джампинг.'],
    ['Traditional land diving inspired bungee jumping.', 'Традиционные прыжки с высоты вдохновили банджи-джампинг.'],
    ['The Eiffel Tower is located in Paris.', 'Эйфелева башня находится в Париже.'],
    ['The Taj Mahal is located there.', 'Тадж-Махал находится там.'],
    ['The Great Wall is located there.', 'Великая Китайская стена находится там.'],
    ['The pyramids are located in Egypt.', 'Пирамиды находятся в Египте.'],
    ['Machu Picchu is located in Peru.', 'Мачу-Пикчу находится в Перу.'],
    ['Petra is located in Jordan.', 'Петра находится в Иордании.'],
    ['Mecca is located in Saudi Arabia.', 'Мекка находится в Саудовской Аравии.'],
    ['The Burj Khalifa.', 'Бурдж-Халифа.'],
    ['Dubai has the Burj Khalifa.', 'В Дубае находится Бурдж-Халифа.'],
    ['Marina Bay Sands is a famous landmark.', 'Marina Bay Sands является знаменитой достопримечательностью.'],
    ['The Sistine Chapel is located there.', 'Сикстинская капелла находится там.'],
    ['St. Peter\'s Basilica is located there.', 'Собор Святого Петра находится там.'],
    ['Big Ben is located in London.', 'Биг-Бен находится в Лондоне.'],
    ['Hollywood is located there.', 'Голливуд находится там.'],
    ['Angel Falls is the world\'s tallest waterfall.', 'Анхель является самым высоким водопадом в мире.'],
    ['Victoria Falls borders Zambia.', 'Водопад Виктория находится у границы Замбии.'],
    ['Victoria Falls is partly in Zimbabwe.', 'Водопад Виктория частично находится в Зимбабве.'],
    ['The Nile River flows through the country.', 'Через страну протекает Нил.'],
    ['The Congo River flows through it.', 'Через страну протекает река Конго.'],
    ['The Congo River flows nearby.', 'Река Конго протекает рядом.'],
    ['The Indus River flows through the country.', 'Через страну протекает Инд.'],
    ['The Mekong River flows through it.', 'Через страну протекает Меконг.'],
    ['The Niger River flows through the country.', 'Через страну протекает Нигер.'],
    ['The Niger River is important there.', 'Река Нигер там очень важна.'],
    ['The Zambezi River flows through the country.', 'Через страну протекает Замбези.'],
    ['The White Nile flows through the country.', 'Через страну протекает Белый Нил.'],
    ['The Danube River flows through Serbia.', 'Через Сербию протекает Дунай.'],
    ['The Tigris and Euphrates rivers flow through the country.', 'Через страну протекают Тигр и Евфрат.'],
    ['The Dead Sea is located there.', 'Там находится Мёртвое море.'],
    ['The Dead Sea borders the country.', 'Страна граничит с Мёртвым морем.'],
    ['Lake Tanganyika borders the country.', 'Страна граничит с озером Танганьика.'],
    ['Lake Malawi is one of Africa\'s largest lakes.', 'Озеро Малави является одним из крупнейших озёр Африки.'],
    ['Lake Nicaragua is one of the largest lakes in the Americas.', 'Озеро Никарагуа является одним из крупнейших озёр Америки.'],
    ['Lake Baikal is the deepest lake on Earth.', 'Байкал является самым глубоким озером на Земле.'],
    ['Lake Ohrid is one of Europe\'s oldest lakes.', 'Охридское озеро является одним из старейших озёр Европы.'],
    ['Lake Assal is one of the saltiest lakes in the world.', 'Озеро Ассаль является одним из самых солёных озёр мира.'],
    ['Lake Atitlan is a famous landmark.', 'Озеро Атитлан является знаменитой достопримечательностью.'],
    ['The Galapagos Islands belong to Ecuador.', 'Галапагосские острова принадлежат Эквадору.'],
    ['Easter Island belongs to Chile.', 'Остров Пасхи принадлежит Чили.'],
    ['Zanzibar belongs to Tanzania.', 'Занзибар принадлежит Танзании.'],
    ['The Great Barrier Reef is located near Australia.', 'Большой Барьерный риф находится рядом с Австралией.'],
    ['The Sundarbans mangrove forest is located there.', 'Там находится мангровый лес Сундарбан.'],
    ['The Amazon rainforest covers much of the country.', 'Амазонские леса покрывают большую часть страны.'],
    ['Rainforests cover much of the land.', 'Тропические леса покрывают большую часть территории.'],
    ['Rainforests cover parts of the country.', 'Тропические леса покрывают часть страны.'],
    ['Rainforests exist in the south.', 'На юге есть тропические леса.'],
    ['Dense rainforests cover much of the land.', 'Густые тропические леса покрывают большую часть территории.'],
    ['Dense jungles cover much of the country.', 'Густые джунгли покрывают большую часть страны.'],
    ['Dense forests cover much of the land.', 'Густые леса покрывают большую часть территории.'],
    ['Much of the country is covered by the Sahara Desert.', 'Большая часть страны покрыта пустыней Сахара.'],
    ['Much of the country is desert.', 'Большая часть страны покрыта пустыней.'],
    ['Much of Chad is desert.', 'Большая часть Чада покрыта пустыней.'],
    ['Much of Niger is covered by desert.', 'Большая часть Нигера покрыта пустыней.'],
    ['Much of Mauritania is desert.', 'Большая часть Мавритании покрыта пустыней.'],
    ['Much of the country consists of steppe.', 'Большая часть страны состоит из степей.'],
    ['Much of the country is steppe.', 'Большая часть страны состоит из степей.'],
    ['The Sahara Desert reaches the country.', 'Пустыня Сахара доходит до этой страны.'],
    ['The Atacama Desert is one of the driest places on Earth.', 'Пустыня Атакама является одним из самых сухих мест на Земле.'],
    ['The Namib Desert.', 'пустыней Намиб.'],
    ['Namibia has the Namib Desert.', 'В Намибии находится пустыня Намиб.'],
    ['Deserts and mountains shape the country.', 'Пустыни и горы формируют облик страны.'],
    ['The Himalayas cover much of the country.', 'Гималаи покрывают большую часть страны.'],
    ['The Himalayas dominate the country.', 'Гималаи доминируют в ландшафте страны.'],
    ['The Alps cover much of the country.', 'Альпы покрывают большую часть страны.'],
    ['The Andes Mountains cross the country.', 'Через страну проходят Анды.'],
    ['The Carpathian Mountains cross the country.', 'Через страну проходят Карпаты.'],
    ['The Caucasus Mountains run through the country.', 'Через страну проходят Кавказские горы.'],
    ['The Atlas Mountains cross the country.', 'Через страну проходят Атласские горы.'],
    ['The Tatra Mountains are located there.', 'Там находятся Татры.'],
    ['Mountains cover most of Kyrgyzstan.', 'Горы покрывают большую часть Кыргызстана.'],
    ['Mountains cover much of North Macedonia.', 'Горы покрывают большую часть Северной Македонии.'],
    ['Mountains cover much of the land.', 'Горы покрывают большую часть территории.'],
    ['Mount Everest is located there.', 'Там находится Эверест.'],
    ['Pakistan is home to K2 mountain.', 'В Пакистане находится гора K2.'],
    ['Mount Kilimanjaro is located there.', 'Там находится Килиманджаро.'],
    ['Mount Cameroon is an active volcano.', 'Гора Камерун является активным вулканом.'],
    ['The Pitons are famous volcanic peaks in Saint Lucia.', 'Питоны — знаменитые вулканические вершины Сент-Люсии.'],
    ['Volcanoes are common there.', 'Вулканы там встречаются часто.'],
    ['Volcanoes shaped many of the islands.', 'Вулканы сформировали многие острова.'],
    ['Volcanoes shaped the landscape.', 'Вулканы сформировали ландшафт.'],
    ['The islands have volcanic origins.', 'Острова имеют вулканическое происхождение.'],
    ['The island has volcanic origins.', 'Остров имеет вулканическое происхождение.'],
    ['Volcanoes surround many cities.', 'Многие города окружены вулканами.'],
    ['Vanuatu has active volcanoes.', 'В Вануату есть активные вулканы.'],
    ['Azerbaijan is called the Land of Fire.', 'Азербайджан называют Страной огней.'],
    ['Cameroon is called Africa in miniature because of its geography.', 'Камерун называют Африкой в миниатюре из-за его географии.'],
    ['Dominica is known as the Nature Island.', 'Доминику называют Островом природы.'],
    ['Grenada is known as the Spice Island.', 'Гренаду называют Островом специй.'],
    ['Rwanda is called the Land of a Thousand Hills.', 'Руанду называют Страной тысячи холмов.'],
    ['Finland is called the Land of a Thousand Lakes.', 'Финляндию называют Страной тысячи озёр.'],
    ['Malawi is called the Warm Heart of Africa.', 'Малави называют Тёплым сердцем Африки.'],
    ['Albania has thousands of old bunkers.', 'В Албании тысячи старых бункеров.'],
    ['The Albanian Riviera is famous for beaches.', 'Албанская Ривьера известна пляжами.'],
    ['Mountains cover much of Albania.', 'Горы покрывают большую часть Албании.'],
    ['Angkor Wat is located in Cambodia.', 'Ангкор-Ват находится в Камбодже.'],
    ['Bagan is famous for ancient temples.', 'Баган известен древними храмами.'],
    ['Ancient temples are located there.', 'Там находятся древние храмы.'],
    ['Ancient Maya ruins are located there.', 'Там находятся древние руины майя.'],
    ['Ancient Maya ruins attract tourists.', 'Древние руины майя привлекают туристов.'],
    ['Ancient Maya civilization flourished in Guatemala.', 'В Гватемале процветала древняя цивилизация майя.'],
    ['Mexico is home to ancient Maya and Aztec sites.', 'В Мексике находятся древние памятники майя и ацтеков.'],
    ['Ancient Mesopotamia was located in Iraq.', 'Древняя Месопотамия находилась в Ираке.'],
    ['Ancient Egyptian civilization is one of the oldest in history.', 'Древнеегипетская цивилизация — одна из старейших в истории.'],
    ['Carthage was located in modern Tunisia.', 'Карфаген находился на территории современной Тунисии.'],
    ['Ancient Troy was located there.', 'Там находилась древняя Троя.'],
    ['The Khmer Empire once ruled much of Southeast Asia.', 'Кхмерская империя когда-то правила большой частью Юго-Восточной Азии.'],
    ['Vatican City is the smallest country in the world.', 'Ватикан — самая маленькая страна в мире.'],
    ['Monaco is one of the world\'s smallest countries.', 'Монако — одна из самых маленьких стран мира.'],
    ['Nauru is one of the world\'s smallest countries.', 'Науру — одна из самых маленьких стран мира.'],
    ['San Marino is surrounded by Italy.', 'Сан-Марино окружён Италией.'],
    ['Lesotho is completely surrounded by South Africa.', 'Лесото полностью окружено Южной Африкой.'],
    ['The entire country lies at high elevation.', 'Вся страна расположена на большой высоте.'],
    ['Much of the Netherlands lies below sea level.', 'Большая часть Нидерландов лежит ниже уровня моря.'],
    ['It is one of the world\'s lowest countries.', 'Это одна из самых низко расположенных стран мира.'],
    ['It has one of the lowest population densities in the world.', 'У страны одна из самых низких плотностей населения в мире.'],
    ['It is one of the least populated countries.', 'Это одна из наименее населённых стран мира.'],
    ['Bangladesh has one of the highest population densities in the world.', 'В Бангладеш одна из самых высоких плотностей населения в мире.'],
    ['Nigeria has the largest population in Africa.', 'В Нигерии самое большое население в Африке.'],
    ['China has the world\'s largest population.', 'В Китае самое большое население в мире.'],
    ['India is the world\'s largest democracy.', 'Индия — крупнейшая демократия мира.'],
    ['Russia is the largest country in the world.', 'Россия — самая большая страна в мире.'],
    ['Canada is the second-largest country in the world.', 'Канада — вторая по площади страна мира.'],
    ['Algeria is the largest country in Africa.', 'Алжир — самая большая страна Африки.'],
    ['Brazil is the largest country in South America.', 'Бразилия — самая большая страна Южной Америки.'],
    ['Kazakhstan is the largest landlocked country in the world.', 'Казахстан — крупнейшая страна мира без выхода к морю.'],
    ['Chile is one of the longest countries in the world.', 'Чили — одна из самых вытянутых стран мира.'],
    ['Kiribati spans across four hemispheres.', 'Кирибати расположена сразу в четырёх полушариях.'],
    ['Istanbul lies in both Europe and Asia.', 'Стамбул расположен и в Европе, и в Азии.'],
    ['Russia spans Europe and Asia.', 'Россия простирается через Европу и Азию.'],
    ['It spans Europe and Asia.', 'Страна простирается через Европу и Азию.'],
    ['The country is doubly landlocked.', 'Страна дважды не имеет выхода к морю.'],
    ['The country is landlocked.', 'Страна не имеет выхода к морю.'],
    ['Laos is Southeast Asia\'s only landlocked country.', 'Лаос — единственная страна Юго-Восточной Азии без выхода к морю.'],
    ['Salar de Uyuni is the world\'s largest salt flat.', 'Салар-де-Уюни — крупнейший солончак мира.'],
    ['Bhutan measures happiness through Gross National Happiness.', 'Бутан измеряет счастье через валовое национальное счастье.'],
    ['Traditional culture remains very strong there.', 'Традиционная культура там остаётся очень сильной.'],
    ['Traditional festivals are important there.', 'Традиционные фестивали там очень важны.'],
    ['Traditional culture remains strong.', 'Традиционная культура остаётся сильной.'],
    ['Nomadic culture remains important.', 'Кочевая культура остаётся важной.'],
    ['Nomadic traditions remain important there.', 'Кочевые традиции там остаются важными.'],
    ['Nomadic traditions remain important.', 'Кочевые традиции остаются важными.'],
    ['Persian culture strongly influenced the region.', 'Персидская культура сильно повлияла на регион.'],
    ['Buddhism is very important there.', 'Буддизм там очень важен.'],
    ['Elephants are important in Thai culture.', 'Слоны важны в тайской культуре.'],
    ['Camels are important in Somali culture.', 'Верблюды важны в сомалийской культуре.'],
    ['The harp is a national symbol.', 'Арфа является национальным символом.'],
    ['The European bison lives there.', 'Там живёт европейский зубр.'],
    ['Mountain gorillas live there.', 'Там живут горные гориллы.'],
    ['Giant tortoises live there.', 'Там живут гигантские черепахи.'],
    ['Komodo dragons live there.', 'Там живут комодские вараны.'],
    ['Lemurs are native to Madagascar.', 'Лемуры являются эндемиками Мадагаскара.'],
    ['Kiwi birds are native there.', 'Птицы киви являются местными для этой страны.'],
    ['Many animals in Madagascar exist nowhere else.', 'Многие животные Мадагаскара больше нигде не встречаются.'],
    ['Marine biodiversity is extremely rich.', 'Морское биоразнообразие там чрезвычайно богато.'],
    ['Football', 'Футбол'],
    ['Basketball', 'Баскетбол'],
    ['Baseball', 'Бейсбол'],
    ['Cricket', 'Крикет'],
    ['Rugby', 'Регби'],
    ['Tourism', 'Туризм'],
    ['Coffee', 'Кофе'],
    ['Cocoa', 'Какао'],
    ['Oil', 'Нефть'],
    ['Gas', 'Газ'],
    ['The country', 'Страна'],
    ['The island', 'Остров'],
    ['The nation', 'Страна'],
    ['the country', 'страна'],
    ['the island', 'остров'],
    ['the nation', 'страна'],
    [' is ', ' — '],
    [' are ', ' — '],
    [' has ', ' имеет '],
    [' have ', ' имеют '],
    [' was ', ' был '],
    [' were ', ' были '],
    [' there.', ' там.'],
  ],
  es: [
    ['is home to', 'alberga'],
    ['parts of', 'partes de'],
    ['Hindu Kush mountains', 'montanas del Hindu Kush'],
    ['tango dancing', 'el tango'],
    ['The country', 'El país'],
    ['The island', 'La isla'],
    ['The nation', 'La nación'],
    ['the country', 'el país'],
    ['the island', 'la isla'],
    ['is the official language.', 'es el idioma oficial.'],
    ['are official languages.', 'son idiomas oficiales.'],
    ['is the capital city.', 'es la capital.'],
    ['Tourism is', 'El turismo es'],
    ['is very popular there.', 'es muy popular allí.'],
    ['is extremely popular there.', 'es extremadamente popular allí.'],
    ['is important there.', 'es importante allí.'],
    ['is important to the economy.', 'es importante para la economía.'],
    ['is located there.', 'se encuentra allí.'],
    ['is located in', 'se encuentra en'],
    ['flows through the country.', 'atraviesa el país.'],
    ['covers much of the country.', 'cubre gran parte del país.'],
    ['belongs to', 'pertenece a'],
    ['consists of', 'está formado por'],
    ['is known for', 'es conocido por'],
    ['is famous for', 'es famoso por'],
    ['has many', 'tiene muchos'],
    ['has large', 'tiene grandes'],
    ['has rich', 'tiene ricos'],
    ['has one of', 'tiene uno de'],
    ['one of the world\'s', 'uno de los del mundo'],
    ['one of Africa\'s', 'uno de los de África'],
    ['largest', 'más grandes'],
    ['smallest', 'más pequeños'],
    ['oldest', 'más antiguos'],
    ['highest', 'más altos'],
    ['lowest', 'más bajos'],
    ['important', 'importante'],
    ['popular', 'popular'],
    ['famous', 'famoso'],
    ['ancient', 'antiguo'],
    ['modern', 'moderno'],
    ['mountains', 'montañas'],
    ['islands', 'islas'],
    ['beaches', 'playas'],
    ['rainforests', 'selvas tropicales'],
    ['desert', 'desierto'],
    ['volcanoes', 'volcanes'],
    ['coastline', 'costa'],
    ['economy', 'economía'],
    ['production', 'producción'],
    ['exports', 'exportaciones'],
    ['culture', 'cultura'],
    ['traditions', 'tradiciones'],
    [' in the world.', ' en el mundo.'],
    [' there.', ' allí.'],
    [' is ', ' es '],
    [' are ', ' son '],
    [' has ', ' tiene '],
    [' have ', ' tienen '],
    [' was ', ' fue '],
    [' were ', ' fueron '],
  ],
  fr: [
    ['is home to', 'abrite'],
    ['parts of', 'des parties de'],
    ['Hindu Kush mountains', 'montagnes de l Hindu Kush'],
    ['tango dancing', 'le tango'],
    ['The country', 'Le pays'],
    ['The island', 'L’île'],
    ['The nation', 'La nation'],
    ['the country', 'le pays'],
    ['the island', 'l’île'],
    ['is the official language.', 'est la langue officielle.'],
    ['are official languages.', 'sont des langues officielles.'],
    ['is the capital city.', 'est la capitale.'],
    ['Tourism is', 'Le tourisme est'],
    ['is very popular there.', 'y est très populaire.'],
    ['is extremely popular there.', 'y est extrêmement populaire.'],
    ['is important there.', 'y est important.'],
    ['is important to the economy.', 'est important pour l’économie.'],
    ['is located there.', 'se trouve là-bas.'],
    ['is located in', 'se trouve en'],
    ['flows through the country.', 'traverse le pays.'],
    ['covers much of the country.', 'couvre une grande partie du pays.'],
    ['belongs to', 'appartient à'],
    ['consists of', 'se compose de'],
    ['is known for', 'est connu pour'],
    ['is famous for', 'est célèbre pour'],
    ['has many', 'a beaucoup de'],
    ['has large', 'possède de grandes'],
    ['has rich', 'possède de riches'],
    ['has one of', 'possède l’un des'],
    ['one of the world\'s', 'l’un des plus du monde'],
    ['one of Africa\'s', 'l’un des plus d’Afrique'],
    ['largest', 'plus grands'],
    ['smallest', 'plus petits'],
    ['oldest', 'plus anciens'],
    ['highest', 'plus élevés'],
    ['lowest', 'plus bas'],
    ['important', 'important'],
    ['popular', 'populaire'],
    ['famous', 'célèbre'],
    ['ancient', 'ancien'],
    ['modern', 'moderne'],
    ['mountains', 'montagnes'],
    ['islands', 'îles'],
    ['beaches', 'plages'],
    ['rainforests', 'forêts tropicales'],
    ['desert', 'désert'],
    ['volcanoes', 'volcans'],
    ['coastline', 'littoral'],
    ['economy', 'économie'],
    ['production', 'production'],
    ['exports', 'exportations'],
    ['culture', 'culture'],
    ['traditions', 'traditions'],
    [' in the world.', ' au monde.'],
    [' there.', ' là-bas.'],
    [' is ', ' est '],
    [' are ', ' sont '],
    [' has ', ' a '],
    [' have ', ' ont '],
    [' was ', ' était '],
    [' were ', ' étaient '],
  ],
  de: [
    ['is home to', 'beherbergt'],
    ['parts of', 'Teile des'],
    ['Hindu Kush mountains', 'Hindukusch-Gebirges'],
    ['tango dancing', 'den Tango'],
    ['The country', 'Das Land'],
    ['The island', 'Die Insel'],
    ['The nation', 'Die Nation'],
    ['the country', 'das Land'],
    ['the island', 'die Insel'],
    ['is the official language.', 'ist die Amtssprache.'],
    ['are official languages.', 'sind Amtssprachen.'],
    ['is the capital city.', 'ist die Hauptstadt.'],
    ['Tourism is', 'Tourismus ist'],
    ['is very popular there.', 'ist dort sehr beliebt.'],
    ['is extremely popular there.', 'ist dort extrem beliebt.'],
    ['is important there.', 'ist dort wichtig.'],
    ['is important to the economy.', 'ist wichtig für die Wirtschaft.'],
    ['is located there.', 'befindet sich dort.'],
    ['is located in', 'befindet sich in'],
    ['flows through the country.', 'fließt durch das Land.'],
    ['covers much of the country.', 'bedeckt einen großen Teil des Landes.'],
    ['belongs to', 'gehört zu'],
    ['consists of', 'besteht aus'],
    ['is known for', 'ist bekannt für'],
    ['is famous for', 'ist berühmt für'],
    ['has many', 'hat viele'],
    ['has large', 'hat große'],
    ['has rich', 'hat reiche'],
    ['has one of', 'hat eines der'],
    ['one of the world\'s', 'eines der weltweit'],
    ['one of Africa\'s', 'eines der afrikanischen'],
    ['largest', 'größten'],
    ['smallest', 'kleinsten'],
    ['oldest', 'ältesten'],
    ['highest', 'höchsten'],
    ['lowest', 'niedrigsten'],
    ['important', 'wichtig'],
    ['popular', 'beliebt'],
    ['famous', 'berühmt'],
    ['ancient', 'antik'],
    ['modern', 'modern'],
    ['mountains', 'Berge'],
    ['islands', 'Inseln'],
    ['beaches', 'Strände'],
    ['rainforests', 'Regenwälder'],
    ['desert', 'Wüste'],
    ['volcanoes', 'Vulkane'],
    ['coastline', 'Küste'],
    ['economy', 'Wirtschaft'],
    ['production', 'Produktion'],
    ['exports', 'Exporte'],
    ['culture', 'Kultur'],
    ['traditions', 'Traditionen'],
    [' in the world.', ' der Welt.'],
    [' there.', ' dort.'],
    [' is ', ' ist '],
    [' are ', ' sind '],
    [' has ', ' hat '],
    [' have ', ' haben '],
    [' was ', ' war '],
    [' were ', ' waren '],
  ],
  ro: [
    ['is home to', 'gazduieste'],
    ['parts of', 'parti din'],
    ['Hindu Kush mountains', 'muntii Hindu Kush'],
    ['tango dancing', 'dansul tango'],
    ['The country', 'Țara'],
    ['The island', 'Insula'],
    ['The nation', 'Națiunea'],
    ['the country', 'țara'],
    ['the island', 'insula'],
    ['is the official language.', 'este limba oficială.'],
    ['are official languages.', 'sunt limbi oficiale.'],
    ['is the capital city.', 'este capitala.'],
    ['Tourism is', 'Turismul este'],
    ['is very popular there.', 'este foarte popular acolo.'],
    ['is extremely popular there.', 'este extrem de popular acolo.'],
    ['is important there.', 'este important acolo.'],
    ['is important to the economy.', 'este important pentru economie.'],
    ['is located there.', 'se află acolo.'],
    ['is located in', 'se află în'],
    ['flows through the country.', 'curge prin țară.'],
    ['covers much of the country.', 'acoperă o mare parte a țării.'],
    ['belongs to', 'aparține de'],
    ['consists of', 'este formată din'],
    ['is known for', 'este cunoscută pentru'],
    ['is famous for', 'este faimoasă pentru'],
    ['has many', 'are multe'],
    ['has large', 'are mari'],
    ['has rich', 'are bogate'],
    ['has one of', 'are una dintre'],
    ['one of the world\'s', 'una dintre cele mai din lume'],
    ['one of Africa\'s', 'una dintre cele mai din Africa'],
    ['largest', 'mari'],
    ['smallest', 'mici'],
    ['oldest', 'vechi'],
    ['highest', 'înalte'],
    ['lowest', 'joase'],
    ['important', 'important'],
    ['popular', 'popular'],
    ['famous', 'faimos'],
    ['ancient', 'antic'],
    ['modern', 'modern'],
    ['mountains', 'munți'],
    ['islands', 'insule'],
    ['beaches', 'plaje'],
    ['rainforests', 'păduri tropicale'],
    ['desert', 'deșert'],
    ['volcanoes', 'vulcani'],
    ['coastline', 'coastă'],
    ['economy', 'economie'],
    ['production', 'producție'],
    ['exports', 'exporturi'],
    ['culture', 'cultură'],
    ['traditions', 'tradiții'],
    [' in the world.', ' din lume.'],
    [' there.', ' acolo.'],
    [' is ', ' este '],
    [' are ', ' sunt '],
    [' has ', ' are '],
    [' have ', ' au '],
    [' was ', ' a fost '],
    [' were ', ' au fost '],
  ],
}

function toReplacementPairs(items: readonly (readonly [string, string])[]) {
  return items.map(([from, to]) => [from, to] as [string, string])
}

const countryNameReplacementMap: Record<Exclude<FactLanguage, 'en'>, Array<[string, string]>> = {
  ru: toReplacementPairs(countryNameReplacementMapSource.ru),
  es: toReplacementPairs(countryNameReplacementMapSource.es),
  fr: toReplacementPairs(countryNameReplacementMapSource.fr),
  de: toReplacementPairs(countryNameReplacementMapSource.de),
  ro: toReplacementPairs(countryNameReplacementMapSource.ro),
}

Object.values(countryNameReplacementMap).forEach((items) => {
  items.sort((first, second) => second[0].length - first[0].length)
})

const residueWordMap: Record<Exclude<FactLanguage, 'en'>, Record<string, string>> = {
  ru: {
    a: '',
    about: 'примерно',
    across: 'через',
    active: 'активный',
    after: 'после',
    all: 'все',
    among: 'среди',
    and: 'и',
    ancient: 'древний',
    associated: 'связана',
    architecture: 'архитектурой',
    are: '',
    army: 'армии',
    at: 'на',
    attract: 'привлекают',
    beaches: 'пляжами',
    became: 'стала',
    because: 'из-за',
    belongs: 'принадлежит',
    between: 'между',
    biodiversity: 'биоразнообразием',
    borders: 'граничит',
    born: 'родился',
    both: 'и',
    built: 'построены',
    buildings: 'зданиями',
    by: '',
    called: 'называют',
    capital: 'столица',
    cars: 'машины',
    center: 'центром',
    central: 'центральной',
    cities: 'городами',
    city: 'город',
    clean: 'чистая',
    climate: 'климат',
    coastline: 'побережье',
    coffee: 'кофе',
    common: 'распространены',
    consists: 'состоит',
    country: 'страна',
    countries: 'стран',
    crossed: 'пересекали',
    culture: 'культурой',
    dracula: 'Дракулой',
    deserts: 'пустынями',
    desert: 'пустыня',
    digitalized: 'цифровизирована',
    divided: 'разделен',
    dominates: 'доминирует',
    economy: 'экономики',
    exports: 'экспорт',
    famous: 'известна',
    for: '',
    forests: 'лесами',
    formerly: 'раньше',
    founded: 'основана',
    from: 'из',
    gas: 'газ',
    has: 'имеет',
    have: 'имеют',
    headquarters: 'штаб-квартира',
    held: 'проводятся',
    helped: 'помогла',
    high: 'высоко',
    highest: 'самых высоких',
    highly: 'сильно',
    history: 'историей',
    home: 'место',
    hosts: 'принимает',
    important: 'важны',
    in: 'в',
    includes: 'включает',
    industries: 'отрасли',
    industry: 'отрасль',
    into: 'на',
    invented: 'изобретен',
    is: '',
    island: 'остров',
    islands: 'островами',
    known: 'известна',
    lakes: 'озерами',
    land: 'земля',
    landlocked: 'без выхода к морю',
    language: 'язык',
    languages: 'языками',
    largest: 'крупнейшая',
    lies: 'лежит',
    live: 'живут',
    located: 'находится',
    major: 'важный',
    main: 'главных',
    many: 'много',
    modern: 'современной',
    most: 'большая часть',
    mountains: 'горы',
    mountain: 'гора',
    much: 'большая часть',
    nation: 'государство',
    national: 'национальный',
    no: 'нет',
    of: '',
    official: 'официальный',
    oil: 'нефть',
    old: 'старые',
    oldest: 'старейших',
    on: 'на',
    one: 'одна',
    originated: 'появился',
    parts: 'части',
    popular: 'популярны',
    production: 'производство',
    rainforests: 'тропическими лесами',
    rainforest: 'тропический лес',
    rebuilt: 'перестроен',
    region: 'регион',
    regions: 'регионы',
    remains: 'остается',
    reserves: 'запасы',
    romanian: 'румынские',
    rich: 'богата',
    routes: 'пути',
    sea: 'море',
    second: 'вторая',
    several: 'несколько',
    smallest: 'маленьких',
    south: 'юге',
    spans: 'охватывает',
    strong: 'сильной',
    technology: 'технологиями',
    the: '',
    there: 'там',
    through: 'через',
    to: 'к',
    tourism: 'туризм',
    tourists: 'туристов',
    traditions: 'традициями',
    two: 'два',
    three: 'три',
    very: 'очень',
    visited: 'посещаемых',
    was: 'был',
    wealthy: 'богатая',
    were: 'были',
    with: 'с',
    world: 'мира',
    worlds: 'мира',
    wine: 'вином',
    producing: 'производящие',
  },
  es: {
    a: 'un',
    about: 'aproximadamente',
    across: 'a traves de',
    active: 'activo',
    after: 'despues de',
    and: 'y',
    ancient: 'antiguo',
    an: 'un',
    architecture: 'arquitectura',
    are: 'son',
    beaches: 'playas',
    became: 'se convirtio',
    belongs: 'pertenece',
    borders: 'limita con',
    born: 'nacio',
    called: 'llamado',
    capital: 'capital',
    cities: 'ciudades',
    city: 'ciudad',
    coastline: 'costa',
    common: 'comunes',
    consists: 'consiste',
    country: 'pais',
    countries: 'paises',
    culture: 'cultura',
    desert: 'desierto',
    economy: 'economia',
    exports: 'exportaciones',
    famous: 'famoso',
    for: 'por',
    football: 'futbol',
    has: 'tiene',
    have: 'tienen',
    held: 'celebradas',
    important: 'importante',
    in: 'en',
    is: 'es',
    island: 'isla',
    islands: 'islas',
    known: 'conocido',
    largest: 'mas grande',
    located: 'ubicado',
    many: 'muchos',
    mountains: 'montanas',
    of: 'de',
    on: 'en',
    official: 'oficial',
    old: 'antiguo',
    oldest: 'mas antiguos',
    one: 'uno',
    popular: 'popular',
    production: 'produccion',
    rich: 'rico',
    the: 'el',
    there: 'alli',
    through: 'a traves de',
    to: 'a',
    tourism: 'turismo',
    two: 'dos',
    three: 'tres',
    very: 'muy',
    was: 'fue',
    were: 'fueron',
    with: 'con',
    world: 'mundo',
  },
  fr: {
    a: 'un',
    about: 'environ',
    across: 'a travers',
    active: 'actif',
    after: 'apres',
    and: 'et',
    ancient: 'ancien',
    an: 'un',
    architecture: 'architecture',
    are: 'sont',
    beaches: 'plages',
    became: 'est devenu',
    belongs: 'appartient',
    borders: 'borde',
    born: 'est ne',
    called: 'appele',
    capital: 'capitale',
    cities: 'villes',
    city: 'ville',
    coastline: 'littoral',
    common: 'courants',
    consists: 'se compose',
    country: 'pays',
    countries: 'pays',
    culture: 'culture',
    desert: 'desert',
    economy: 'economie',
    exports: 'exportations',
    famous: 'celebre',
    for: 'pour',
    has: 'a',
    have: 'ont',
    held: 'organisees',
    important: 'important',
    in: 'en',
    is: 'est',
    island: 'ile',
    islands: 'iles',
    known: 'connu',
    largest: 'plus grand',
    located: 'situe',
    many: 'nombreux',
    mountains: 'montagnes',
    of: 'de',
    on: 'sur',
    official: 'officiel',
    old: 'ancien',
    oldest: 'plus anciens',
    one: 'un',
    popular: 'populaire',
    production: 'production',
    rich: 'riche',
    the: 'le',
    there: 'la-bas',
    through: 'a travers',
    to: 'a',
    tourism: 'tourisme',
    two: 'deux',
    three: 'trois',
    very: 'tres',
    was: 'etait',
    were: 'etaient',
    with: 'avec',
    world: 'monde',
  },
  de: {
    a: 'ein',
    about: 'etwa',
    across: 'durch',
    active: 'aktiv',
    after: 'nach',
    and: 'und',
    ancient: 'alt',
    an: 'ein',
    architecture: 'Architektur',
    are: 'sind',
    beaches: 'Strande',
    buildings: 'Gebäude',
    became: 'wurde',
    belongs: 'gehort',
    borders: 'grenzt an',
    born: 'wurde geboren',
    called: 'genannt',
    capital: 'Hauptstadt',
    cities: 'Stadte',
    city: 'Stadt',
    coastline: 'Kuste',
    common: 'verbreitet',
    consists: 'besteht',
    country: 'Land',
    countries: 'Lander',
    culture: 'Kultur',
    desert: 'Wuste',
    economy: 'Wirtschaft',
    exports: 'Exporte',
    famous: 'beruhmt',
    for: 'fur',
    has: 'hat',
    have: 'haben',
    held: 'ausgetragen',
    important: 'wichtig',
    in: 'in',
    is: 'ist',
    island: 'Insel',
    islands: 'Inseln',
    known: 'bekannt',
    largest: 'grosste',
    located: 'liegt',
    many: 'viele',
    mountains: 'Berge',
    of: 'von',
    on: 'auf',
    official: 'offiziell',
    old: 'alt',
    oldest: 'altesten',
    one: 'eines',
    popular: 'beliebt',
    production: 'Produktion',
    rich: 'reich',
    the: 'das',
    there: 'dort',
    through: 'durch',
    to: 'zu',
    tourism: 'Tourismus',
    two: 'zwei',
    three: 'drei',
    very: 'sehr',
    was: 'war',
    were: 'waren',
    with: 'mit',
    world: 'Welt',
  },
  ro: {
    a: 'un',
    about: 'aproximativ',
    across: 'prin',
    active: 'activ',
    after: 'dupa',
    and: 'si',
    ancient: 'antic',
    an: 'un',
    architecture: 'arhitectura',
    are: 'sunt',
    beaches: 'plaje',
    became: 'a devenit',
    belongs: 'apartine',
    borders: 'se invecineaza cu',
    born: 's-a nascut',
    called: 'numit',
    capital: 'capitala',
    cities: 'orase',
    city: 'oras',
    coastline: 'coasta',
    common: 'comune',
    consists: 'consta',
    country: 'tara',
    countries: 'tari',
    culture: 'cultura',
    desert: 'desert',
    economy: 'economie',
    exports: 'exporturi',
    famous: 'faimos',
    for: 'pentru',
    football: 'fotbal',
    has: 'are',
    have: 'au',
    held: 'organizate',
    important: 'important',
    in: 'in',
    is: 'este',
    island: 'insula',
    islands: 'insule',
    known: 'cunoscut',
    largest: 'cea mai mare',
    located: 'situat',
    many: 'multe',
    mountains: 'munti',
    of: 'de',
    on: 'pe',
    official: 'oficial',
    old: 'vechi',
    oldest: 'cele mai vechi',
    one: 'una',
    popular: 'popular',
    production: 'productie',
    rich: 'bogat',
    the: '',
    there: 'acolo',
    through: 'prin',
    to: 'la',
    tourism: 'turism',
    two: 'doua',
    three: 'trei',
    very: 'foarte',
    was: 'a fost',
    were: 'au fost',
    with: 'cu',
    world: 'lume',
  },
}

const residuePhraseMap: Record<Exclude<FactLanguage, 'en'>, Array<[RegExp, string]>> = {
  ru: [
    [/\bis associated with\b/gi, 'связана с'],
    [/\b— associated\b/gi, 'связана'],
    [/\bDracula legends\b/gi, 'легендами о Дракуле'],
    [/\bCarpathian Mountains\b/gi, 'Карпаты'],
    [/\binternet speeds\b/gi, 'скорости интернета'],
    [/\bis home to\b/gi, 'здесь находятся'],
    [/\bis made up of\b/gi, 'состоит из'],
    [/\bwas formerly called\b/gi, 'раньше называлась'],
    [/\bis called\b/gi, 'называют'],
    [/\bis known for\b/gi, 'известна'],
    [/\bis famous for\b/gi, 'известна'],
    [/\bis located\b/gi, 'находится'],
    [/\bare located\b/gi, 'находятся'],
    [/\bthe capital city\b/gi, 'столица'],
    [/\bthe official language\b/gi, 'официальный язык'],
    [/\bofficial languages\b/gi, 'официальные языки'],
    [/\bWorld War II\b/gi, 'Второй мировой войны'],
    [/\bSilk Road\b/gi, 'Шелкового пути'],
    [/\bHindu Kush\b/gi, 'Гиндукуша'],
    [/\bPersian Gulf\b/gi, 'Персидского залива'],
    [/\bIndian Ocean\b/gi, 'Индийского океана'],
    [/\bAtlantic Ocean\b/gi, 'Атлантического океана'],
    [/\bPacific Ocean\b/gi, 'Тихого океана'],
    [/\bGreat Barrier Reef\b/gi, 'Большой Барьерный риф'],
    [/\bGreat Rift Valley\b/gi, 'Великая рифтовая долина'],
    [/\bGross National Happiness\b/gi, 'валовое национальное счастье'],
    [/\bFormula 1\b/gi, 'Формула-1'],
    [/\bGame of Thrones\b/gi, 'Игра престолов'],
    [/\bLord of the Rings\b/gi, 'Властелин колец'],
    [/\bleft-side driving\b/gi, 'левостороннее движение'],
    [/\blegal tender\b/gi, 'законное платежное средство'],
    [/\bglobal financial hub\b/gi, 'мировой финансовый центр'],
    [/\btechnology startups\b/gi, 'технологическими стартапами'],
    [/\bmarine biodiversity\b/gi, 'морское биоразнообразие'],
    [/\brising sea levels\b/gi, 'рост уровня моря'],
    [/\bcoral atolls\b/gi, 'коралловые атоллы'],
    [/\btropical rainforests\b/gi, 'тропические леса'],
    [/\bmud volcanoes\b/gi, 'грязевые вулканы'],
    [/\bthermal baths\b/gi, 'термальные купальни'],
    [/\bNorthern lights\b/gi, 'северное сияние'],
    [/\bmidnight sun\b/gi, 'полуночное солнце'],
  ],
  es: [
    [/\bMost of\b/gi, 'La mayor parte de'],
    [/\bcovered by\b/gi, 'cubierto por'],
    [/\bSahara Desert\b/gi, 'desierto del Sahara'],
    [/\bOil and gas\b/gi, 'El petroleo y el gas'],
    [/\bSki tourism\b/gi, 'El turismo de esqui'],
    [/\bvery popular\b/gi, 'muy popular'],
    [/\bthe island\b/gi, 'la isla'],
    [/\bcapital city\b/gi, 'capital'],
    [/\bofficial languages\b/gi, 'idiomas oficiales'],
    [/\bofficial language\b/gi, 'idioma oficial'],
    [/\bGold mining\b/gi, 'La mineria de oro'],
    [/\bWildlife tourism\b/gi, 'El turismo de vida silvestre'],
    [/\bRose oil production\b/gi, 'La produccion de aceite de rosa'],
  ],
  fr: [
    [/\bMost of\b/gi, 'La majeure partie de'],
    [/\bcovered by\b/gi, 'couverte par'],
    [/\bSahara Desert\b/gi, 'desert du Sahara'],
    [/\bOil and gas\b/gi, 'Le petrole et le gaz'],
    [/\bTextile production\b/gi, 'La production textile'],
    [/\bGold mining\b/gi, 'L extraction de l or'],
    [/\bWildlife tourism\b/gi, 'Le tourisme animalier'],
    [/\bRose oil production\b/gi, 'La production d huile de rose'],
    [/\bofficial languages\b/gi, 'langues officielles'],
    [/\bofficial language\b/gi, 'langue officielle'],
    [/\bcapital city\b/gi, 'capitale'],
  ],
  de: [
    [/\bofficial languages\b/gi, 'Amtssprachen'],
    [/\bofficial language\b/gi, 'Amtssprache'],
    [/\bhundreds of languages\b/gi, 'Hunderte von Sprachen'],
    [/\bmodern buildings\b/gi, 'moderne Gebäude'],
    [/\boften used\b/gi, 'oft genutzt'],
    [/\bmountain regions\b/gi, 'Bergregionen'],
    [/\bis home to\b/gi, 'beherbergt'],
    [/\bK2 mountain\b/gi, 'den Berg K2'],
    [/\bmodern skyline\b/gi, 'moderne Skyline'],
    [/\bare spoken\b/gi, 'werden gesprochen'],
  ],
  ro: [
    [/\bMost of\b/gi, 'Cea mai mare parte din'],
    [/\bcovered by\b/gi, 'acoperita de'],
    [/\bSahara Desert\b/gi, 'desertul Sahara'],
    [/\bOil and gas\b/gi, 'Petrolul si gazele'],
    [/\bSki tourism\b/gi, 'Turismul de schi'],
    [/\bvery popular\b/gi, 'foarte popular'],
    [/\bthe island\b/gi, 'insula'],
    [/\bTextile production\b/gi, 'Productia textila'],
    [/\bofficial languages\b/gi, 'limbi oficiale'],
    [/\bofficial language\b/gi, 'limba oficiala'],
    [/\bcapital city\b/gi, 'capitala'],
    [/\bGold mining\b/gi, 'Mineritul aurului'],
    [/\bWildlife tourism\b/gi, 'Turismul de fauna salbatica'],
    [/\bRose oil production\b/gi, 'Productia de ulei de trandafir'],
  ],
}

function replaceWholeWord(text: string, from: string, to: string) {
  return text.replace(new RegExp(`\\b${from.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi'), to)
}

function localizeCountryNames(text: string, language: Exclude<FactLanguage, 'en'>) {
  return countryNameReplacementMap[language].reduce(
    (currentText, [from, to]) => replaceWholeWord(currentText, from, to),
    text,
  )
}

function replaceResidueWords(text: string, language: Exclude<FactLanguage, 'en'>) {
  const words = residueWordMap[language]

  return Object.entries(words).reduce((currentText, [from, to]) => {
    return replaceWholeWord(currentText, from, to)
  }, text)
}

function normalizeTranslatedFact(text: string) {
  return text
    .replace(/\s+/g, ' ')
    .replace(/\s+([.,:;!?])/g, '$1')
    .replace(/(^|[.!?]\s+)([a-zа-я])/g, (match) => match.toLocaleUpperCase())
    .trim()
}

const commonEnglishResiduePattern =
  /\b(the|country|countries|city|cities|island|islands|mountain|mountains|desert|tourism|exports|production|official|language|languages|coastline|borders|located|famous|known|popular|ancient|modern|important|there|world|capital|associated|legends|covered|most|three|two|an|on|home|used|spoken|buildings|regions|main|into|by|developed|programmers|filming|parts|dancing|places|earth|coffee|export|cotton|wildlife|traditional|festivals|surrounded|freed|slaves)\b/gi

function stripResidualEnglish(text: string, language: Exclude<FactLanguage, 'en'>) {
  if (language === 'ru') {
    return text.replace(/\b[A-Za-z][A-Za-z'-]*\b/g, '')
  }

  return text.replace(commonEnglishResiduePattern, '')
}

function translateProvidedFact(fact: string, language: Exclude<FactLanguage, 'en'>) {
  let translated = fact

  residuePhraseMap[language].forEach(([from, to]) => {
    translated = translated.replace(from, to)
  })

  factReplacementMap[language].forEach(([from, to]) => {
    translated = translated.split(from).join(to)
  })

  translated = localizeCountryNames(translated, language)

  residuePhraseMap[language].forEach(([from, to]) => {
    translated = translated.replace(from, to)
  })

  translated = replaceResidueWords(translated, language)
  translated = stripResidualEnglish(translated, language)

  return normalizeTranslatedFact(translated)
}

export function getProvidedCountryFacts(code: string, language: FactLanguage) {
  const facts = providedCountryFacts[code]

  if (!facts) return undefined
  if (language === 'en') return facts

  return providedFactTranslations[code]?.[language] ?? translatedFactOverrides[code]?.[language] ?? facts.map((fact) => translateProvidedFact(fact, language))
}
